name: Build Windows binary

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 🛒
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'

      - name: Build Windows binary 🔨
        run: |
          GOOS=windows GOARCH=amd64 go build -o trust-me-seal-cli.exe main.go

      - name: Upload binary artifact 💎
        uses: actions/upload-artifact@v4
        with:
          name: trust-me-seal-cli
          path: ./bin
